"""
Test synthesizer for merging clustered tests using LLM
"""

import asyncio
import aiohttp
from typing import List, Dict, Any, Optional
from loguru import logger

from app.config import config
from app.utils.exceptions import SynthesisError
from app.utils.streaming import StreamingQueue, SSEStream


class TestSynthesizer:
    """Synthesizes final tests from clusters using LLM"""

    def __init__(self, streaming_queue: Optional[StreamingQueue] = None):
        self.streaming_queue = streaming_queue
        self.session: Optional[aiohttp.ClientSession] = None

    async def __aenter__(self):
        """Async context manager entry"""
        self.session = aiohttp.ClientSession(
            timeout=aiohttp.ClientTimeout(total=config.REQUEST_TIMEOUT)
        )
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        """Async context manager exit"""
        if self.session:
            await self.session.close()

    async def synthesize_tests(
            self,
            clusters: Dict[int, List[str]],
            function_name: str,
            function_code: str
    ) -> str:
        """
        Synthesize final test suite from clusters

        Args:
            clusters: Dictionary mapping cluster_id to list of test codes
            function_name: Name of the function being tested
            function_code: Source code of the function

        Returns:
            Final synthesized test code
        """
        if not clusters:
            raise SynthesisError("No clusters provided for synthesis")

        # Send synthesis start event
        if self.streaming_queue:
            await self.streaming_queue.put(
                await SSEStream.send_synthesis_start_event(
                    clusters_to_synthesize=len(clusters)
                )
            )

        logger.info(f"Synthesizing tests from {len(clusters)} clusters")

        # Build synthesis prompt
        prompt = self._build_synthesis_prompt(clusters, function_name, function_code)

        # Call LLM for synthesis
        synthesized_code = await self._call_synthesis_llm(prompt)

        # Clean and validate
        final_code = self._clean_synthesis_output(synthesized_code, function_name)

        return final_code

    def _build_synthesis_prompt(
            self,
            clusters: Dict[int, List[str]],
            function_name: str,
            function_code: str
    ) -> str:
        """Build synthesis prompt"""

        # Prepare cluster summaries
        cluster_summaries = []
        for cluster_id, tests in clusters.items():
            if cluster_id == -1:
                continue  # Skip noise

            cluster_summaries.append(f"""
### Cluster {cluster_id} ({len(tests)} similar tests)
```python
{tests[0]}
```
... and {len(tests) - 1} similar variations
""")

        clusters_text = "\n".join(cluster_summaries)

        prompt = f"""You are synthesizing a final, comprehensive test suite.

You have received **{len(clusters)} clusters** of similar test cases generated by multiple AI models. Your task is to create a **unified, non-redundant, high-quality test suite** that:

1. **Eliminates redundancy** - Merge similar tests from each cluster into one excellent test
2. **Preserves diversity** - Keep tests that cover different scenarios
3. **Maximizes coverage** - Ensure all edge cases, errors, and normal cases are covered
4. **Maintains quality** - Follow pytest best practices

## Function Under Test
python
{function_code}

## Clustered Tests
{clusters_text}

## Your Task
Synthesize these clusters into a **final test suite** for `{function_name}`. 

**Guidelines:**
- For each cluster, create ONE excellent test that represents the best aspects of all tests in that cluster
- Ensure test names are descriptive: `test_{function_name}_<scenario>`
- Include docstrings explaining what each test validates
- Use proper assertions and pytest features
- Add necessary imports at the top
- Organize tests logically (positive → negative → edge → security → performance)

**Output Format:**
python
import pytest
# Add other necessary imports

def test_{function_name}_scenario1():
    \"\"\"Description of what this test validates.\"\"\"
    # Test implementation
    assert condition

def test_{function_name}_scenario2():
    \"\"\"Description of what this test validates.\"\"\"
    # Test implementation
    assert condition

Generate the complete, final test suite now:
"""

        return prompt

    async def _call_synthesis_llm(self, prompt: str) -> str:
        """
        Call LLM for synthesis with streaming thinking

        Args:
            prompt: Synthesis prompt

        Returns:
            Synthesized test code
        """
        # Use the best model for synthesis (gemini-2.0-flash)
        model_id = config.SYNTHESIS_MODEL
        model_config = config.LLM_MODELS[model_id]
        api_base = config.LLM_API_BASES[model_config["provider"]]

        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {config.LLM_API_KEY}"
        }

        payload = {
            "model": model_config["api_name"],
            "messages": [
                {"role": "system", "content": "You are an expert at synthesizing high-quality test suites."},
                {"role": "user", "content": prompt}
            ],
            "temperature": 0.5,  # Lower temperature for more focused synthesis
            "max_tokens": 6000,
            "stream": True
        }

        full_response = ""

        try:
            async with self.session.post(
                    f"{api_base}/chat/completions",
                    headers=headers,
                    json=payload
            ) as response:
                response.raise_for_status()

                async for line in response.content:
                    line = line.decode('utf-8').strip()

                    if not line or line == "data: [DONE]":
                        continue

                    if line.startswith("data: "):
                        try:
                            import json
                            data = json.loads(line[6:])

                            if "choices" in data and len(data["choices"]) > 0:
                                delta = data["choices"][0].get("delta", {})
                                content = delta.get("content", "")

                                if content:
                                    full_response += content

                                    # Send thinking chunk
                                    if self.streaming_queue:
                                        await self.streaming_queue.put(
                                            await SSEStream.send_synthesis_thinking_event(
                                                thinking_chunk=content
                                            )
                                        )

                        except json.JSONDecodeError:
                            continue

            logger.info(f"Synthesis complete: {len(full_response)} characters")
            return full_response

        except Exception as e:
            logger.error(f"Synthesis LLM call failed: {e}", exc_info=True)
            raise SynthesisError(f"Failed to call synthesis LLM: {str(e)}")

    def _clean_synthesis_output(self, raw_output: str, function_name: str) -> str:
        """
        Clean and validate synthesis output

        Args:
            raw_output: Raw LLM output
            function_name: Function name for validation

        Returns:
            Cleaned test code
        """
        # Remove markdown code fences
        cleaned = raw_output

        # Ensure imports are present
        if "import pytest" not in cleaned:
            cleaned = "import pytest\n\n" + cleaned

        # Validate that we have test functions
        if f"def test_{function_name}" not in cleaned and "def test_" not in cleaned:
            logger.warning("Synthesis output doesn't contain expected test functions")

        return cleaned.strip()
